/*Kilimba Analytix*/

package com.mcm2.tracking;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;




/**
 * BloodSlide generated by hbm2java
 */
@Entity
@Table(name="blood_slide"
    ,schema="public"
)
public class BloodSlide  implements java.io.Serializable
 {


private Integer id;
private String patientId;
private String firstName;
private String middleName;
private String surname;
private boolean knowHamlet;
private Date dateCollected;
private Date timeCollected;
private String interviewerInitials;
private Date dateRead;
private Integer reader;
private String pfAsexual;
private String pfGametocyte;
private String pfSexual;
private String pmAsexual;
private String pmGametocyte;
private String pmSexual;
private String poAsexual;
private String poGametocyte;
private String poSexual;
private String pvAsexual;
private String pvGametocyte;
private String pvSexual;
private String parasiteSeen;
private Integer numTrophozoites;
private Integer numWbcAsexual;
private Integer numGametocytes;
private Integer numWbcSexual;
private Integer numInfectedRbc;
private Integer totalRbc;
private String comments;
private String labTechInitials;
private Hamlet hamlet;

    public BloodSlide() {
    }



     @Id @GeneratedValue(strategy=IDENTITY)

    

    @Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    

    @Column(name="patient_id", nullable=false)
    public String getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    

    @Column(name="first_name", nullable=false)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    

    @Column(name="middle_name")
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    

    @Column(name="surname", nullable=false)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    

    @Column(name="know_hamlet", nullable=false)
    public boolean isKnowHamlet() {
        return this.knowHamlet;
    }
    
    public void setKnowHamlet(boolean knowHamlet) {
        this.knowHamlet = knowHamlet;
    }

    @Temporal(TemporalType.DATE)

    @Column(name="date_collected", nullable=false, length=13)
    public Date getDateCollected() {
        return this.dateCollected;
    }
    
    public void setDateCollected(Date dateCollected) {
        this.dateCollected = dateCollected;
    }

    @Temporal(TemporalType.TIME)

    @Column(name="time_collected", nullable=false, length=15)
    public Date getTimeCollected() {
        return this.timeCollected;
    }
    
    public void setTimeCollected(Date timeCollected) {
        this.timeCollected = timeCollected;
    }

    

    @Column(name="interviewer_initials", nullable=false, length=2)
    public String getInterviewerInitials() {
        return this.interviewerInitials;
    }
    
    public void setInterviewerInitials(String interviewerInitials) {
        this.interviewerInitials = interviewerInitials;
    }

    @Temporal(TemporalType.DATE)

    @Column(name="date_read", nullable=false, length=13)
    public Date getDateRead() {
        return this.dateRead;
    }
    
    public void setDateRead(Date dateRead) {
        this.dateRead = dateRead;
    }

    

    @Column(name="reader", nullable=false)
    public Integer getReader() {
        return this.reader;
    }
    
    public void setReader(Integer reader) {
        this.reader = reader;
    }

    

    @Column(name="pf_asexual", nullable=false)
    public String getPfAsexual() {
        return this.pfAsexual;
    }
    
    public void setPfAsexual(String pfAsexual) {
        this.pfAsexual = pfAsexual;
    }

    

    @Column(name="pf_gametocyte", nullable=false)
    public String getPfGametocyte() {
        return this.pfGametocyte;
    }
    
    public void setPfGametocyte(String pfGametocyte) {
        this.pfGametocyte = pfGametocyte;
    }

    

    @Column(name="pf_sexual", nullable=false)
    public String getPfSexual() {
        return this.pfSexual;
    }
    
    public void setPfSexual(String pfSexual) {
        this.pfSexual = pfSexual;
    }

    

    @Column(name="pm_asexual", nullable=false)
    public String getPmAsexual() {
        return this.pmAsexual;
    }
    
    public void setPmAsexual(String pmAsexual) {
        this.pmAsexual = pmAsexual;
    }

    

    @Column(name="pm_gametocyte", nullable=false)
    public String getPmGametocyte() {
        return this.pmGametocyte;
    }
    
    public void setPmGametocyte(String pmGametocyte) {
        this.pmGametocyte = pmGametocyte;
    }

    

    @Column(name="pm_sexual", nullable=false)
    public String getPmSexual() {
        return this.pmSexual;
    }
    
    public void setPmSexual(String pmSexual) {
        this.pmSexual = pmSexual;
    }

    

    @Column(name="po_asexual", nullable=false)
    public String getPoAsexual() {
        return this.poAsexual;
    }
    
    public void setPoAsexual(String poAsexual) {
        this.poAsexual = poAsexual;
    }

    

    @Column(name="po_gametocyte", nullable=false)
    public String getPoGametocyte() {
        return this.poGametocyte;
    }
    
    public void setPoGametocyte(String poGametocyte) {
        this.poGametocyte = poGametocyte;
    }

    

    @Column(name="po_sexual", nullable=false)
    public String getPoSexual() {
        return this.poSexual;
    }
    
    public void setPoSexual(String poSexual) {
        this.poSexual = poSexual;
    }

    

    @Column(name="pv_asexual", nullable=false)
    public String getPvAsexual() {
        return this.pvAsexual;
    }
    
    public void setPvAsexual(String pvAsexual) {
        this.pvAsexual = pvAsexual;
    }

    

    @Column(name="pv_gametocyte", nullable=false)
    public String getPvGametocyte() {
        return this.pvGametocyte;
    }
    
    public void setPvGametocyte(String pvGametocyte) {
        this.pvGametocyte = pvGametocyte;
    }

    

    @Column(name="pv_sexual", nullable=false)
    public String getPvSexual() {
        return this.pvSexual;
    }
    
    public void setPvSexual(String pvSexual) {
        this.pvSexual = pvSexual;
    }

    

    @Column(name="parasite_seen", nullable=false)
    public String getParasiteSeen() {
        return this.parasiteSeen;
    }
    
    public void setParasiteSeen(String parasiteSeen) {
        this.parasiteSeen = parasiteSeen;
    }

    

    @Column(name="num_trophozoites", nullable=false)
    public Integer getNumTrophozoites() {
        return this.numTrophozoites;
    }
    
    public void setNumTrophozoites(Integer numTrophozoites) {
        this.numTrophozoites = numTrophozoites;
    }

    

    @Column(name="num_wbc_asexual", nullable=false)
    public Integer getNumWbcAsexual() {
        return this.numWbcAsexual;
    }
    
    public void setNumWbcAsexual(Integer numWbcAsexual) {
        this.numWbcAsexual = numWbcAsexual;
    }

    

    @Column(name="num_gametocytes", nullable=false)
    public Integer getNumGametocytes() {
        return this.numGametocytes;
    }
    
    public void setNumGametocytes(Integer numGametocytes) {
        this.numGametocytes = numGametocytes;
    }

    

    @Column(name="num_wbc_sexual", nullable=false)
    public Integer getNumWbcSexual() {
        return this.numWbcSexual;
    }
    
    public void setNumWbcSexual(Integer numWbcSexual) {
        this.numWbcSexual = numWbcSexual;
    }

    

    @Column(name="num_infected_rbc", nullable=false)
    public Integer getNumInfectedRbc() {
        return this.numInfectedRbc;
    }
    
    public void setNumInfectedRbc(Integer numInfectedRbc) {
        this.numInfectedRbc = numInfectedRbc;
    }

    

    @Column(name="total_rbc", nullable=false)
    public Integer getTotalRbc() {
        return this.totalRbc;
    }
    
    public void setTotalRbc(Integer totalRbc) {
        this.totalRbc = totalRbc;
    }

    

    @Column(name="comments")
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    

    @Column(name="lab_tech_initials", nullable=false, length=2)
    public String getLabTechInitials() {
        return this.labTechInitials;
    }
    
    public void setLabTechInitials(String labTechInitials) {
        this.labTechInitials = labTechInitials;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="hamlet")
    public Hamlet getHamlet() {
        return this.hamlet;
    }
    
    public void setHamlet(Hamlet hamlet) {
        this.hamlet = hamlet;
    }



public boolean equals(Object o) {
         if (this == o)
         return true;
		 if ( (o == null ) )
		 return false;
		 if ( !(o instanceof BloodSlide) )
		 return false;

		 BloodSlide that = ( BloodSlide ) o;

		 return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) );

   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );

         return result;
     }


}

