/*Kilimba Analytix*/

package com.mcm2.tracking;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;




/**
 * HealthFacility generated by hbm2java
 */
@Entity
@Table(name="health_facility"
    ,schema="public"
)
public class HealthFacility  implements java.io.Serializable
 {


private Integer id;
private String facilityId;
private String facilityName;
private String facilityType;
private Hamlet hamlet;
private Set<Healthworker> healthworkers = new HashSet<Healthworker>(0);

    public HealthFacility() {
    }



     @Id @GeneratedValue(strategy=IDENTITY)

    

    @Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    

    @Column(name="facility_id", nullable=false)
    public String getFacilityId() {
        return this.facilityId;
    }
    
    public void setFacilityId(String facilityId) {
        this.facilityId = facilityId;
    }

    

    @Column(name="facility_name", nullable=false)
    public String getFacilityName() {
        return this.facilityName;
    }
    
    public void setFacilityName(String facilityName) {
        this.facilityName = facilityName;
    }

    

    @Column(name="facility_type", nullable=false)
    public String getFacilityType() {
        return this.facilityType;
    }
    
    public void setFacilityType(String facilityType) {
        this.facilityType = facilityType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="hamlet")
    public Hamlet getHamlet() {
        return this.hamlet;
    }
    
    public void setHamlet(Hamlet hamlet) {
        this.hamlet = hamlet;
    }

@OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="healthFacility")
    public Set<Healthworker> getHealthworkers() {
        return this.healthworkers;
    }
    
    public void setHealthworkers(Set<Healthworker> healthworkers) {
        this.healthworkers = healthworkers;
    }



public boolean equals(Object o) {
         if (this == o)
         return true;
		 if ( (o == null ) )
		 return false;
		 if ( !(o instanceof HealthFacility) )
		 return false;

		 HealthFacility that = ( HealthFacility ) o;

		 return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) );

   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );

         return result;
     }


}

