/*Kilimba Analytix*/

package com.mcm2.tracking;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;




/**
 * Patient generated by hbm2java
 */
@Entity
@Table(name="patient"
    ,schema="public"
)
public class Patient  implements java.io.Serializable
 {


private Integer patientId;
private Integer identifier;
private String firstName;
private String middleName;
private String lastName;
private Date dateOfBirth;
private String sex;
private Integer hamlet;
private String street;
private Set<PatientResults> patientResultses = new HashSet<PatientResults>(0);

    public Patient() {
    }



     @Id @GeneratedValue(strategy=IDENTITY)

    

    @Column(name="patient_id", nullable=false)
    public Integer getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    

    @Column(name="identifier", nullable=false)
    public Integer getIdentifier() {
        return this.identifier;
    }
    
    public void setIdentifier(Integer identifier) {
        this.identifier = identifier;
    }

    

    @Column(name="first_name", nullable=false)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    

    @Column(name="middle_name")
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    

    @Column(name="last_name", nullable=false)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Temporal(TemporalType.DATE)

    @Column(name="date_of_birth", length=13)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    

    @Column(name="sex")
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    

    @Column(name="hamlet")
    public Integer getHamlet() {
        return this.hamlet;
    }
    
    public void setHamlet(Integer hamlet) {
        this.hamlet = hamlet;
    }

    

    @Column(name="street")
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }

@OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="patient")
    public Set<PatientResults> getPatientResultses() {
        return this.patientResultses;
    }
    
    public void setPatientResultses(Set<PatientResults> patientResultses) {
        this.patientResultses = patientResultses;
    }



public boolean equals(Object o) {
         if (this == o)
         return true;
		 if ( (o == null ) )
		 return false;
		 if ( !(o instanceof Patient) )
		 return false;

		 Patient that = ( Patient ) o;

		 return ( (this.getPatientId()==that.getPatientId()) || ( this.getPatientId()!=null && that.getPatientId()!=null && this.getPatientId().equals(that.getPatientId()) ) );

   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getPatientId() == null ? 0 : this.getPatientId().hashCode() );

         return result;
     }


}

