/*Kilimba Analytix*/

package com.mcm2.tracking;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;




/**
 * PatientResults generated by hbm2java
 */
@Entity
@Table(name="patient_results"
    ,schema="public"
)
public class PatientResults  implements java.io.Serializable
 {


private Integer resultsId;
private Date testDate;
private String mrdtControl;
private String mrdtPalcifarum;
private String mrdtPan;
private String mrdtIntepretation;
private String bsResult;
private String bsOtherTests;
private Patient patient;

    public PatientResults() {
    }



     @Id @GeneratedValue(strategy=IDENTITY)

    

    @Column(name="results_id", nullable=false)
    public Integer getResultsId() {
        return this.resultsId;
    }
    
    public void setResultsId(Integer resultsId) {
        this.resultsId = resultsId;
    }

    @Temporal(TemporalType.DATE)

    @Column(name="test_date", length=13)
    public Date getTestDate() {
        return this.testDate;
    }
    
    public void setTestDate(Date testDate) {
        this.testDate = testDate;
    }

    

    @Column(name="mrdt_control")
    public String getMrdtControl() {
        return this.mrdtControl;
    }
    
    public void setMrdtControl(String mrdtControl) {
        this.mrdtControl = mrdtControl;
    }

    

    @Column(name="mrdt_palcifarum")
    public String getMrdtPalcifarum() {
        return this.mrdtPalcifarum;
    }
    
    public void setMrdtPalcifarum(String mrdtPalcifarum) {
        this.mrdtPalcifarum = mrdtPalcifarum;
    }

    

    @Column(name="mrdt_pan")
    public String getMrdtPan() {
        return this.mrdtPan;
    }
    
    public void setMrdtPan(String mrdtPan) {
        this.mrdtPan = mrdtPan;
    }

    

    @Column(name="mrdt_intepretation")
    public String getMrdtIntepretation() {
        return this.mrdtIntepretation;
    }
    
    public void setMrdtIntepretation(String mrdtIntepretation) {
        this.mrdtIntepretation = mrdtIntepretation;
    }

    

    @Column(name="bs_result")
    public String getBsResult() {
        return this.bsResult;
    }
    
    public void setBsResult(String bsResult) {
        this.bsResult = bsResult;
    }

    

    @Column(name="bs_other_tests")
    public String getBsOtherTests() {
        return this.bsOtherTests;
    }
    
    public void setBsOtherTests(String bsOtherTests) {
        this.bsOtherTests = bsOtherTests;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="patient")
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }



public boolean equals(Object o) {
         if (this == o)
         return true;
		 if ( (o == null ) )
		 return false;
		 if ( !(o instanceof PatientResults) )
		 return false;

		 PatientResults that = ( PatientResults ) o;

		 return ( (this.getResultsId()==that.getResultsId()) || ( this.getResultsId()!=null && that.getResultsId()!=null && this.getResultsId().equals(that.getResultsId()) ) );

   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getResultsId() == null ? 0 : this.getResultsId().hashCode() );

         return result;
     }


}

