/*Kilimba Analytix*/

package com.mcm2.tracking;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;




/**
 * Ward generated by hbm2java
 */
@Entity
@Table(name="ward"
    ,schema="public"
)
public class Ward  implements java.io.Serializable
 {


private short wardId;
private String wardName;
private District district;
private Set<Village> villages = new HashSet<Village>(0);

    public Ward() {
    }



     @Id @GeneratedValue(strategy=IDENTITY)

    

    @Column(name="ward_id", nullable=false)
    public short getWardId() {
        return this.wardId;
    }
    
    public void setWardId(short wardId) {
        this.wardId = wardId;
    }

    

    @Column(name="ward_name")
    public String getWardName() {
        return this.wardName;
    }
    
    public void setWardName(String wardName) {
        this.wardName = wardName;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="district")
    public District getDistrict() {
        return this.district;
    }
    
    public void setDistrict(District district) {
        this.district = district;
    }

@OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="ward")
    public Set<Village> getVillages() {
        return this.villages;
    }
    
    public void setVillages(Set<Village> villages) {
        this.villages = villages;
    }



public boolean equals(Object o) {
         if (this == o)
         return true;
		 if ( (o == null ) )
		 return false;
		 if ( !(o instanceof Ward) )
		 return false;

		 Ward that = ( Ward ) o;

		 return (this.getWardId()==that.getWardId());

   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + this.getWardId();

         return result;
     }


}

