/*Kilimba Analytix*/

package com.mcm2.tracking.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
import com.mcm2.tracking.service.BloodSlideService;
import java.io.*;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.hibernate.TypeMismatchException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartHttpServletRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.util.WMMultipartUtils;
import com.wavemaker.runtime.util.WMRuntimeUtils;
import com.wordnik.swagger.annotations.*;
import com.mcm2.tracking.*;
import com.mcm2.tracking.service.*;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

/**
 * Controller object for domain model class BloodSlide.
 * @see com.mcm2.tracking.BloodSlide
 */
@RestController(value = "Tracking.BloodSlideController")
@RequestMapping("/tracking/BloodSlide")
@Api(description = "Exposes APIs to work with BloodSlide resource.", value = "BloodSlideController")
public class BloodSlideController {

    private static final Logger LOGGER = LoggerFactory.getLogger(BloodSlideController.class);

    @Autowired
    @Qualifier("tracking.BloodSlideService")
    private BloodSlideService bloodSlideService;

    @RequestMapping(value = "/search", method = RequestMethod.POST)
    @ApiOperation(value = "Returns the list of BloodSlide instances matching the search criteria.")
    public Page<BloodSlide> findBloodSlides(Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering BloodSlides list");
        return bloodSlideService.findAll(queryFilters, pageable);
    }

    @RequestMapping(value = "/", method = RequestMethod.GET)
    @ApiOperation(value = "Returns the list of BloodSlide instances.")
    public Page<BloodSlide> getBloodSlides(Pageable pageable) {
        LOGGER.debug("Rendering BloodSlides list");
        return bloodSlideService.findAll(pageable);
    }

    @RequestMapping(value = "/{id:.+}", method = RequestMethod.GET)
    @ApiOperation(value = "Returns the BloodSlide instance associated with the given id.")
    public BloodSlide getBloodSlide(@PathVariable("id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Getting BloodSlide with id: {}", id);
        BloodSlide instance = bloodSlideService.findById(id);
        LOGGER.debug("BloodSlide details with id: {}", instance);
        return instance;
    }

    @RequestMapping(value = "/{id:.+}", method = RequestMethod.DELETE)
    @ApiOperation(value = "Deletes the BloodSlide instance associated with the given id.")
    public boolean deleteBloodSlide(@PathVariable("id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Deleting BloodSlide with id: {}", id);
        BloodSlide deleted = bloodSlideService.delete(id);
        return deleted != null;
    }

    @RequestMapping(value = "/{id:.+}", method = RequestMethod.PUT)
    @ApiOperation(value = "Updates the BloodSlide instance associated with the given id.")
    public BloodSlide editBloodSlide(@PathVariable("id") Integer id, @RequestBody BloodSlide instance) throws EntityNotFoundException {
        LOGGER.debug("Editing BloodSlide with id: {}", instance.getId());
        instance.setId(id);
        instance = bloodSlideService.update(instance);
        LOGGER.debug("BloodSlide details with id: {}", instance);
        return instance;
    }

    @RequestMapping(value = "/", method = RequestMethod.POST)
    @ApiOperation(value = "Creates a new BloodSlide instance.")
    public BloodSlide createBloodSlide(@RequestBody BloodSlide instance) {
        LOGGER.debug("Create BloodSlide with information: {}", instance);
        instance = bloodSlideService.create(instance);
        LOGGER.debug("Created BloodSlide with information: {}", instance);
        return instance;
    }

    /**
	 * This setter method should only be used by unit tests
	 * 
	 * @param service
	 */
    protected void setBloodSlideService(BloodSlideService service) {
        this.bloodSlideService = service;
    }

    @RequestMapping(value = "/count", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Returns the total count of BloodSlide instances.")
    public Long countAllBloodSlides() {
        LOGGER.debug("counting BloodSlides");
        Long count = bloodSlideService.countAll();
        return count;
    }
}
