/*Kilimba Analytix*/

package com.mcm2.tracking.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
import com.mcm2.tracking.service.DistrictService;
import com.mcm2.tracking.service.WardService;
import java.io.*;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.hibernate.TypeMismatchException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartHttpServletRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.util.WMMultipartUtils;
import com.wavemaker.runtime.util.WMRuntimeUtils;
import com.wordnik.swagger.annotations.*;
import com.mcm2.tracking.*;
import com.mcm2.tracking.service.*;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

/**
 * Controller object for domain model class District.
 * @see com.mcm2.tracking.District
 */
@RestController(value = "Tracking.DistrictController")
@RequestMapping("/tracking/District")
@Api(description = "Exposes APIs to work with District resource.", value = "DistrictController")
public class DistrictController {

    private static final Logger LOGGER = LoggerFactory.getLogger(DistrictController.class);

    @Autowired
    @Qualifier("tracking.DistrictService")
    private DistrictService districtService;

    @Autowired
    @Qualifier("tracking.WardService")
    private WardService wardService;

    @RequestMapping(value = "/search", method = RequestMethod.POST)
    @ApiOperation(value = "Returns the list of District instances matching the search criteria.")
    public Page<District> findDistricts(Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering Districts list");
        return districtService.findAll(queryFilters, pageable);
    }

    @RequestMapping(value = "/", method = RequestMethod.GET)
    @ApiOperation(value = "Returns the list of District instances.")
    public Page<District> getDistricts(Pageable pageable) {
        LOGGER.debug("Rendering Districts list");
        return districtService.findAll(pageable);
    }

    @RequestMapping(value = "/{id:.+}", method = RequestMethod.GET)
    @ApiOperation(value = "Returns the District instance associated with the given id.")
    public District getDistrict(@PathVariable("id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Getting District with id: {}", id);
        District instance = districtService.findById(id);
        LOGGER.debug("District details with id: {}", instance);
        return instance;
    }

    @RequestMapping(value = "/{id:.+}", method = RequestMethod.DELETE)
    @ApiOperation(value = "Deletes the District instance associated with the given id.")
    public boolean deleteDistrict(@PathVariable("id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Deleting District with id: {}", id);
        District deleted = districtService.delete(id);
        return deleted != null;
    }

    @RequestMapping(value = "/{id:.+}", method = RequestMethod.PUT)
    @ApiOperation(value = "Updates the District instance associated with the given id.")
    public District editDistrict(@PathVariable("id") Integer id, @RequestBody District instance) throws EntityNotFoundException {
        LOGGER.debug("Editing District with id: {}", instance.getId());
        instance.setId(id);
        instance = districtService.update(instance);
        LOGGER.debug("District details with id: {}", instance);
        return instance;
    }

    @RequestMapping(value = "/{id:.+}/wards", method = RequestMethod.GET)
    @ApiOperation(value = "Gets the wards instance associated with the given id.")
    public Page<Ward> findAssociatedwards(Pageable pageable, @PathVariable("id") Integer id) {
        LOGGER.debug("Fetching all associated wards");
        return wardService.findAssociatedValues(id, "district", "id", pageable);
    }

    @RequestMapping(value = "/", method = RequestMethod.POST)
    @ApiOperation(value = "Creates a new District instance.")
    public District createDistrict(@RequestBody District instance) {
        LOGGER.debug("Create District with information: {}", instance);
        instance = districtService.create(instance);
        LOGGER.debug("Created District with information: {}", instance);
        return instance;
    }

    /**
	 * This setter method should only be used by unit tests
	 * 
	 * @param service
	 */
    protected void setDistrictService(DistrictService service) {
        this.districtService = service;
    }

    @RequestMapping(value = "/count", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Returns the total count of District instances.")
    public Long countAllDistricts() {
        LOGGER.debug("counting Districts");
        Long count = districtService.countAll();
        return count;
    }
}
