/*Kilimba Analytix*/

package com.mcm2.tracking.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.*;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.mcm2.tracking.*;


/**
 * ServiceImpl object for domain model class BloodSlide.
 * @see com.mcm2.tracking.BloodSlide
 */
@Service("tracking.BloodSlideService")
public class BloodSlideServiceImpl implements BloodSlideService {


    private static final Logger LOGGER = LoggerFactory.getLogger(BloodSlideServiceImpl.class);

    @Autowired
    @Qualifier("tracking.BloodSlideDao")
    private WMGenericDao<BloodSlide, Integer> wmGenericDao;
    public void setWMGenericDao(WMGenericDao<BloodSlide, Integer> wmGenericDao){
        this.wmGenericDao = wmGenericDao;
    }
     @Transactional(readOnly = true, value = "trackingTransactionManager")
     public Page<BloodSlide> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable){
          LOGGER.debug("Fetching all associated");
          return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
     }

    @Transactional(value = "trackingTransactionManager")
    @Override
    public BloodSlide create(BloodSlide bloodslide) {
        LOGGER.debug("Creating a new bloodslide with information: {}" , bloodslide);
        return this.wmGenericDao.create(bloodslide);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "trackingTransactionManager")
    @Override
    public BloodSlide delete(Integer bloodslideId) throws EntityNotFoundException {
        LOGGER.debug("Deleting bloodslide with id: {}" , bloodslideId);
        BloodSlide deleted = this.wmGenericDao.findById(bloodslideId);
        if (deleted == null) {
            LOGGER.debug("No bloodslide found with id: {}" , bloodslideId);
            throw new EntityNotFoundException(String.valueOf(bloodslideId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(readOnly = true, value = "trackingTransactionManager")
    @Override
    public Page<BloodSlide> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all bloodslides");
        return this.wmGenericDao.search(queryFilters, pageable);
    }
    
    @Transactional(readOnly = true, value = "trackingTransactionManager")
    @Override
    public Page<BloodSlide> findAll(Pageable pageable) {
        LOGGER.debug("Finding all bloodslides");
        return this.wmGenericDao.search(null, pageable);
    }

    @Transactional(readOnly = true, value = "trackingTransactionManager")
    @Override
    public BloodSlide findById(Integer id) throws EntityNotFoundException {
        LOGGER.debug("Finding bloodslide by id: {}" , id);
        BloodSlide bloodslide=this.wmGenericDao.findById(id);
        if(bloodslide==null){
            LOGGER.debug("No bloodslide found with id: {}" , id);
            throw new EntityNotFoundException(String.valueOf(id));
        }
        return bloodslide;
    }
    @Transactional(rollbackFor = EntityNotFoundException.class, value = "trackingTransactionManager")
    @Override
    public BloodSlide update(BloodSlide updated) throws EntityNotFoundException {
        LOGGER.debug("Updating bloodslide with information: {}" , updated);
        this.wmGenericDao.update(updated);
        return this.wmGenericDao.findById((Integer)updated.getId());
    }

    @Transactional(readOnly = true, value = "trackingTransactionManager")
    @Override
    public long countAll() {
        return this.wmGenericDao.count();
    }
}


