/*Kilimba Analytix*/

package com.mcm2.tracking.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.mcm2.tracking.*;

/**
 * Service object for domain model class BloodSlide.
 * @see com.mcm2.tracking.BloodSlide
 */

public interface BloodSlideService {
   /**
	 * Creates a new bloodslide.
	 * 
	 * @param created
	 *            The information of the created bloodslide.
	 * @return The created bloodslide.
	 */
	public BloodSlide create(BloodSlide created);

	/**
	 * Deletes a bloodslide.
	 * 
	 * @param bloodslideId
	 *            The id of the deleted bloodslide.
	 * @return The deleted bloodslide.
	 * @throws EntityNotFoundException
	 *             if no bloodslide is found with the given id.
	 */
	public BloodSlide delete(Integer bloodslideId) throws EntityNotFoundException;

	/**
	 * Finds all bloodslides.
	 * 
	 * @return A list of bloodslides.
	 */
	public Page<BloodSlide> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<BloodSlide> findAll(Pageable pageable);
	
	/**
	 * Finds bloodslide by id.
	 * 
	 * @param id
	 *            The id of the wanted bloodslide.
	 * @return The found bloodslide. If no bloodslide is found, this method returns
	 *         null.
	 */
	public BloodSlide findById(Integer id) throws EntityNotFoundException;
	/**
	 * Updates the information of a bloodslide.
	 * 
	 * @param updated
	 *            The information of the updated bloodslide.
	 * @return The updated bloodslide.
	 * @throws EntityNotFoundException
	 *             if no bloodslide is found with given id.
	 */
	public BloodSlide update(BloodSlide updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the bloodslides in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the bloodslide.
	 */

	public long countAll();


    public Page<BloodSlide> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

