/*Kilimba Analytix*/

package com.mcm2.tracking.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.mcm2.tracking.*;

/**
 * Service object for domain model class District.
 * @see com.mcm2.tracking.District
 */

public interface DistrictService {
   /**
	 * Creates a new district.
	 * 
	 * @param created
	 *            The information of the created district.
	 * @return The created district.
	 */
	public District create(District created);

	/**
	 * Deletes a district.
	 * 
	 * @param districtId
	 *            The id of the deleted district.
	 * @return The deleted district.
	 * @throws EntityNotFoundException
	 *             if no district is found with the given id.
	 */
	public District delete(Integer districtId) throws EntityNotFoundException;

	/**
	 * Finds all districts.
	 * 
	 * @return A list of districts.
	 */
	public Page<District> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<District> findAll(Pageable pageable);
	
	/**
	 * Finds district by id.
	 * 
	 * @param id
	 *            The id of the wanted district.
	 * @return The found district. If no district is found, this method returns
	 *         null.
	 */
	public District findById(Integer id) throws EntityNotFoundException;
	/**
	 * Updates the information of a district.
	 * 
	 * @param updated
	 *            The information of the updated district.
	 * @return The updated district.
	 * @throws EntityNotFoundException
	 *             if no district is found with given id.
	 */
	public District update(District updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the districts in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the district.
	 */

	public long countAll();


    public Page<District> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

