/*Kilimba Analytix*/

package com.mcm2.tracking.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.*;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.mcm2.tracking.*;


/**
 * ServiceImpl object for domain model class District.
 * @see com.mcm2.tracking.District
 */
@Service("tracking.DistrictService")
public class DistrictServiceImpl implements DistrictService {


    private static final Logger LOGGER = LoggerFactory.getLogger(DistrictServiceImpl.class);

    @Autowired
    @Qualifier("tracking.DistrictDao")
    private WMGenericDao<District, Integer> wmGenericDao;
    public void setWMGenericDao(WMGenericDao<District, Integer> wmGenericDao){
        this.wmGenericDao = wmGenericDao;
    }
     @Transactional(readOnly = true, value = "trackingTransactionManager")
     public Page<District> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable){
          LOGGER.debug("Fetching all associated");
          return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
     }

    @Transactional(value = "trackingTransactionManager")
    @Override
    public District create(District district) {
        LOGGER.debug("Creating a new district with information: {}" , district);
        return this.wmGenericDao.create(district);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "trackingTransactionManager")
    @Override
    public District delete(Integer districtId) throws EntityNotFoundException {
        LOGGER.debug("Deleting district with id: {}" , districtId);
        District deleted = this.wmGenericDao.findById(districtId);
        if (deleted == null) {
            LOGGER.debug("No district found with id: {}" , districtId);
            throw new EntityNotFoundException(String.valueOf(districtId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(readOnly = true, value = "trackingTransactionManager")
    @Override
    public Page<District> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all districts");
        return this.wmGenericDao.search(queryFilters, pageable);
    }
    
    @Transactional(readOnly = true, value = "trackingTransactionManager")
    @Override
    public Page<District> findAll(Pageable pageable) {
        LOGGER.debug("Finding all districts");
        return this.wmGenericDao.search(null, pageable);
    }

    @Transactional(readOnly = true, value = "trackingTransactionManager")
    @Override
    public District findById(Integer id) throws EntityNotFoundException {
        LOGGER.debug("Finding district by id: {}" , id);
        District district=this.wmGenericDao.findById(id);
        if(district==null){
            LOGGER.debug("No district found with id: {}" , id);
            throw new EntityNotFoundException(String.valueOf(id));
        }
        return district;
    }
    @Transactional(rollbackFor = EntityNotFoundException.class, value = "trackingTransactionManager")
    @Override
    public District update(District updated) throws EntityNotFoundException {
        LOGGER.debug("Updating district with information: {}" , updated);
        this.wmGenericDao.update(updated);
        return this.wmGenericDao.findById((Integer)updated.getId());
    }

    @Transactional(readOnly = true, value = "trackingTransactionManager")
    @Override
    public long countAll() {
        return this.wmGenericDao.count();
    }
}


