/*Kilimba Analytix*/

package com.mcm2.tracking.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.mcm2.tracking.*;

/**
 * Service object for domain model class Hamlet.
 * @see com.mcm2.tracking.Hamlet
 */

public interface HamletService {
   /**
	 * Creates a new hamlet.
	 * 
	 * @param created
	 *            The information of the created hamlet.
	 * @return The created hamlet.
	 */
	public Hamlet create(Hamlet created);

	/**
	 * Deletes a hamlet.
	 * 
	 * @param hamletId
	 *            The id of the deleted hamlet.
	 * @return The deleted hamlet.
	 * @throws EntityNotFoundException
	 *             if no hamlet is found with the given id.
	 */
	public Hamlet delete(Integer hamletId) throws EntityNotFoundException;

	/**
	 * Finds all hamlets.
	 * 
	 * @return A list of hamlets.
	 */
	public Page<Hamlet> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<Hamlet> findAll(Pageable pageable);
	
	/**
	 * Finds hamlet by id.
	 * 
	 * @param id
	 *            The id of the wanted hamlet.
	 * @return The found hamlet. If no hamlet is found, this method returns
	 *         null.
	 */
	public Hamlet findById(Integer id) throws EntityNotFoundException;
	/**
	 * Updates the information of a hamlet.
	 * 
	 * @param updated
	 *            The information of the updated hamlet.
	 * @return The updated hamlet.
	 * @throws EntityNotFoundException
	 *             if no hamlet is found with given id.
	 */
	public Hamlet update(Hamlet updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the hamlets in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the hamlet.
	 */

	public long countAll();


    public Page<Hamlet> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

