/*Kilimba Analytix*/

package com.mcm2.tracking.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.mcm2.tracking.*;

/**
 * Service object for domain model class Healthworker.
 * @see com.mcm2.tracking.Healthworker
 */

public interface HealthworkerService {
   /**
	 * Creates a new healthworker.
	 * 
	 * @param created
	 *            The information of the created healthworker.
	 * @return The created healthworker.
	 */
	public Healthworker create(Healthworker created);

	/**
	 * Deletes a healthworker.
	 * 
	 * @param healthworkerId
	 *            The id of the deleted healthworker.
	 * @return The deleted healthworker.
	 * @throws EntityNotFoundException
	 *             if no healthworker is found with the given id.
	 */
	public Healthworker delete(Integer healthworkerId) throws EntityNotFoundException;

	/**
	 * Finds all healthworkers.
	 * 
	 * @return A list of healthworkers.
	 */
	public Page<Healthworker> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<Healthworker> findAll(Pageable pageable);
	
	/**
	 * Finds healthworker by id.
	 * 
	 * @param id
	 *            The id of the wanted healthworker.
	 * @return The found healthworker. If no healthworker is found, this method returns
	 *         null.
	 */
	public Healthworker findById(Integer id) throws EntityNotFoundException;
	/**
	 * Updates the information of a healthworker.
	 * 
	 * @param updated
	 *            The information of the updated healthworker.
	 * @return The updated healthworker.
	 * @throws EntityNotFoundException
	 *             if no healthworker is found with given id.
	 */
	public Healthworker update(Healthworker updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the healthworkers in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the healthworker.
	 */

	public long countAll();


    public Page<Healthworker> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

