/*Kilimba Analytix*/

package com.mcm2.tracking.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.mcm2.tracking.*;

/**
 * Service object for domain model class HealthFacility.
 * @see com.mcm2.tracking.HealthFacility
 */

public interface HealthFacilityService {
   /**
	 * Creates a new healthfacility.
	 * 
	 * @param created
	 *            The information of the created healthfacility.
	 * @return The created healthfacility.
	 */
	public HealthFacility create(HealthFacility created);

	/**
	 * Deletes a healthfacility.
	 * 
	 * @param healthfacilityId
	 *            The id of the deleted healthfacility.
	 * @return The deleted healthfacility.
	 * @throws EntityNotFoundException
	 *             if no healthfacility is found with the given id.
	 */
	public HealthFacility delete(Integer healthfacilityId) throws EntityNotFoundException;

	/**
	 * Finds all healthfacilitys.
	 * 
	 * @return A list of healthfacilitys.
	 */
	public Page<HealthFacility> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<HealthFacility> findAll(Pageable pageable);
	
	/**
	 * Finds healthfacility by id.
	 * 
	 * @param id
	 *            The id of the wanted healthfacility.
	 * @return The found healthfacility. If no healthfacility is found, this method returns
	 *         null.
	 */
	public HealthFacility findById(Integer id) throws EntityNotFoundException;
	/**
	 * Updates the information of a healthfacility.
	 * 
	 * @param updated
	 *            The information of the updated healthfacility.
	 * @return The updated healthfacility.
	 * @throws EntityNotFoundException
	 *             if no healthfacility is found with given id.
	 */
	public HealthFacility update(HealthFacility updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the healthfacilitys in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the healthfacility.
	 */

	public long countAll();


    public Page<HealthFacility> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

