/*Kilimba Analytix*/

package com.mcm2.tracking.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.*;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.mcm2.tracking.*;


/**
 * ServiceImpl object for domain model class HealthFacility.
 * @see com.mcm2.tracking.HealthFacility
 */
@Service("tracking.HealthFacilityService")
public class HealthFacilityServiceImpl implements HealthFacilityService {


    private static final Logger LOGGER = LoggerFactory.getLogger(HealthFacilityServiceImpl.class);

    @Autowired
    @Qualifier("tracking.HealthFacilityDao")
    private WMGenericDao<HealthFacility, Integer> wmGenericDao;
    public void setWMGenericDao(WMGenericDao<HealthFacility, Integer> wmGenericDao){
        this.wmGenericDao = wmGenericDao;
    }
     @Transactional(readOnly = true, value = "trackingTransactionManager")
     public Page<HealthFacility> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable){
          LOGGER.debug("Fetching all associated");
          return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
     }

    @Transactional(value = "trackingTransactionManager")
    @Override
    public HealthFacility create(HealthFacility healthfacility) {
        LOGGER.debug("Creating a new healthfacility with information: {}" , healthfacility);
        return this.wmGenericDao.create(healthfacility);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "trackingTransactionManager")
    @Override
    public HealthFacility delete(Integer healthfacilityId) throws EntityNotFoundException {
        LOGGER.debug("Deleting healthfacility with id: {}" , healthfacilityId);
        HealthFacility deleted = this.wmGenericDao.findById(healthfacilityId);
        if (deleted == null) {
            LOGGER.debug("No healthfacility found with id: {}" , healthfacilityId);
            throw new EntityNotFoundException(String.valueOf(healthfacilityId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(readOnly = true, value = "trackingTransactionManager")
    @Override
    public Page<HealthFacility> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all healthfacilitys");
        return this.wmGenericDao.search(queryFilters, pageable);
    }
    
    @Transactional(readOnly = true, value = "trackingTransactionManager")
    @Override
    public Page<HealthFacility> findAll(Pageable pageable) {
        LOGGER.debug("Finding all healthfacilitys");
        return this.wmGenericDao.search(null, pageable);
    }

    @Transactional(readOnly = true, value = "trackingTransactionManager")
    @Override
    public HealthFacility findById(Integer id) throws EntityNotFoundException {
        LOGGER.debug("Finding healthfacility by id: {}" , id);
        HealthFacility healthfacility=this.wmGenericDao.findById(id);
        if(healthfacility==null){
            LOGGER.debug("No healthfacility found with id: {}" , id);
            throw new EntityNotFoundException(String.valueOf(id));
        }
        return healthfacility;
    }
    @Transactional(rollbackFor = EntityNotFoundException.class, value = "trackingTransactionManager")
    @Override
    public HealthFacility update(HealthFacility updated) throws EntityNotFoundException {
        LOGGER.debug("Updating healthfacility with information: {}" , updated);
        this.wmGenericDao.update(updated);
        return this.wmGenericDao.findById((Integer)updated.getId());
    }

    @Transactional(readOnly = true, value = "trackingTransactionManager")
    @Override
    public long countAll() {
        return this.wmGenericDao.count();
    }
}


