/*Kilimba Analytix*/

package com.mcm2.tracking.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.mcm2.tracking.*;

/**
 * Service object for domain model class Patient.
 * @see com.mcm2.tracking.Patient
 */

public interface PatientService {
   /**
	 * Creates a new patient.
	 * 
	 * @param created
	 *            The information of the created patient.
	 * @return The created patient.
	 */
	public Patient create(Patient created);

	/**
	 * Deletes a patient.
	 * 
	 * @param patientId
	 *            The id of the deleted patient.
	 * @return The deleted patient.
	 * @throws EntityNotFoundException
	 *             if no patient is found with the given id.
	 */
	public Patient delete(Integer patientId) throws EntityNotFoundException;

	/**
	 * Finds all patients.
	 * 
	 * @return A list of patients.
	 */
	public Page<Patient> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<Patient> findAll(Pageable pageable);
	
	/**
	 * Finds patient by id.
	 * 
	 * @param id
	 *            The id of the wanted patient.
	 * @return The found patient. If no patient is found, this method returns
	 *         null.
	 */
	public Patient findById(Integer id) throws EntityNotFoundException;
	/**
	 * Updates the information of a patient.
	 * 
	 * @param updated
	 *            The information of the updated patient.
	 * @return The updated patient.
	 * @throws EntityNotFoundException
	 *             if no patient is found with given id.
	 */
	public Patient update(Patient updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the patients in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the patient.
	 */

	public long countAll();


    public Page<Patient> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

