/*Kilimba Analytix*/

package com.mcm2.tracking.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.*;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.mcm2.tracking.*;


/**
 * ServiceImpl object for domain model class Village.
 * @see com.mcm2.tracking.Village
 */
@Service("tracking.VillageService")
public class VillageServiceImpl implements VillageService {


    private static final Logger LOGGER = LoggerFactory.getLogger(VillageServiceImpl.class);

    @Autowired
    @Qualifier("tracking.VillageDao")
    private WMGenericDao<Village, Integer> wmGenericDao;
    public void setWMGenericDao(WMGenericDao<Village, Integer> wmGenericDao){
        this.wmGenericDao = wmGenericDao;
    }
     @Transactional(readOnly = true, value = "trackingTransactionManager")
     public Page<Village> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable){
          LOGGER.debug("Fetching all associated");
          return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
     }

    @Transactional(value = "trackingTransactionManager")
    @Override
    public Village create(Village village) {
        LOGGER.debug("Creating a new village with information: {}" , village);
        return this.wmGenericDao.create(village);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "trackingTransactionManager")
    @Override
    public Village delete(Integer villageId) throws EntityNotFoundException {
        LOGGER.debug("Deleting village with id: {}" , villageId);
        Village deleted = this.wmGenericDao.findById(villageId);
        if (deleted == null) {
            LOGGER.debug("No village found with id: {}" , villageId);
            throw new EntityNotFoundException(String.valueOf(villageId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(readOnly = true, value = "trackingTransactionManager")
    @Override
    public Page<Village> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all villages");
        return this.wmGenericDao.search(queryFilters, pageable);
    }
    
    @Transactional(readOnly = true, value = "trackingTransactionManager")
    @Override
    public Page<Village> findAll(Pageable pageable) {
        LOGGER.debug("Finding all villages");
        return this.wmGenericDao.search(null, pageable);
    }

    @Transactional(readOnly = true, value = "trackingTransactionManager")
    @Override
    public Village findById(Integer id) throws EntityNotFoundException {
        LOGGER.debug("Finding village by id: {}" , id);
        Village village=this.wmGenericDao.findById(id);
        if(village==null){
            LOGGER.debug("No village found with id: {}" , id);
            throw new EntityNotFoundException(String.valueOf(id));
        }
        return village;
    }
    @Transactional(rollbackFor = EntityNotFoundException.class, value = "trackingTransactionManager")
    @Override
    public Village update(Village updated) throws EntityNotFoundException {
        LOGGER.debug("Updating village with information: {}" , updated);
        this.wmGenericDao.update(updated);
        return this.wmGenericDao.findById((Integer)updated.getVillageId());
    }

    @Transactional(readOnly = true, value = "trackingTransactionManager")
    @Override
    public long countAll() {
        return this.wmGenericDao.count();
    }
}


